# Regenerate the sample data via a manual trigger

name: Regenerate Sample Data
on:
  workflow_dispatch:

jobs:
  regenerate:
    name: Regenerate sample data
    runs-on: self-hosted
    if: github.repository == 'Climate-REF/ref-sample-data'
    permissions:
      contents: read
    steps:
      - name: Checkout source code from Github
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Run the regeneration
        uses: ./.github/actions/regenerate
